require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BaseproductsController do

  # This should return the minimal set of attributes required to create a valid
  # Baseproduct. As you add validations to Baseproduct, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BaseproductsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all baseproducts as @baseproducts" do
      baseproduct = Baseproduct.create! valid_attributes
      get :index, {}, valid_session
      assigns(:baseproducts).should eq([baseproduct])
    end
  end

  describe "GET show" do
    it "assigns the requested baseproduct as @baseproduct" do
      baseproduct = Baseproduct.create! valid_attributes
      get :show, {:id => baseproduct.to_param}, valid_session
      assigns(:baseproduct).should eq(baseproduct)
    end
  end

  describe "GET new" do
    it "assigns a new baseproduct as @baseproduct" do
      get :new, {}, valid_session
      assigns(:baseproduct).should be_a_new(Baseproduct)
    end
  end

  describe "GET edit" do
    it "assigns the requested baseproduct as @baseproduct" do
      baseproduct = Baseproduct.create! valid_attributes
      get :edit, {:id => baseproduct.to_param}, valid_session
      assigns(:baseproduct).should eq(baseproduct)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Baseproduct" do
        expect {
          post :create, {:baseproduct => valid_attributes}, valid_session
        }.to change(Baseproduct, :count).by(1)
      end

      it "assigns a newly created baseproduct as @baseproduct" do
        post :create, {:baseproduct => valid_attributes}, valid_session
        assigns(:baseproduct).should be_a(Baseproduct)
        assigns(:baseproduct).should be_persisted
      end

      it "redirects to the created baseproduct" do
        post :create, {:baseproduct => valid_attributes}, valid_session
        response.should redirect_to(Baseproduct.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved baseproduct as @baseproduct" do
        # Trigger the behavior that occurs when invalid params are submitted
        Baseproduct.any_instance.stub(:save).and_return(false)
        post :create, {:baseproduct => { "name" => "invalid value" }}, valid_session
        assigns(:baseproduct).should be_a_new(Baseproduct)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Baseproduct.any_instance.stub(:save).and_return(false)
        post :create, {:baseproduct => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested baseproduct" do
        baseproduct = Baseproduct.create! valid_attributes
        # Assuming there are no other baseproducts in the database, this
        # specifies that the Baseproduct created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Baseproduct.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => baseproduct.to_param, :baseproduct => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested baseproduct as @baseproduct" do
        baseproduct = Baseproduct.create! valid_attributes
        put :update, {:id => baseproduct.to_param, :baseproduct => valid_attributes}, valid_session
        assigns(:baseproduct).should eq(baseproduct)
      end

      it "redirects to the baseproduct" do
        baseproduct = Baseproduct.create! valid_attributes
        put :update, {:id => baseproduct.to_param, :baseproduct => valid_attributes}, valid_session
        response.should redirect_to(baseproduct)
      end
    end

    describe "with invalid params" do
      it "assigns the baseproduct as @baseproduct" do
        baseproduct = Baseproduct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Baseproduct.any_instance.stub(:save).and_return(false)
        put :update, {:id => baseproduct.to_param, :baseproduct => { "name" => "invalid value" }}, valid_session
        assigns(:baseproduct).should eq(baseproduct)
      end

      it "re-renders the 'edit' template" do
        baseproduct = Baseproduct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Baseproduct.any_instance.stub(:save).and_return(false)
        put :update, {:id => baseproduct.to_param, :baseproduct => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested baseproduct" do
      baseproduct = Baseproduct.create! valid_attributes
      expect {
        delete :destroy, {:id => baseproduct.to_param}, valid_session
      }.to change(Baseproduct, :count).by(-1)
    end

    it "redirects to the baseproducts list" do
      baseproduct = Baseproduct.create! valid_attributes
      delete :destroy, {:id => baseproduct.to_param}, valid_session
      response.should redirect_to(baseproducts_url)
    end
  end

end
