require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EventplatesController do

  # This should return the minimal set of attributes required to create a valid
  # Eventplate. As you add validations to Eventplate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "eventplanner_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EventplatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all eventplates as @eventplates" do
      eventplate = Eventplate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:eventplates).should eq([eventplate])
    end
  end

  describe "GET show" do
    it "assigns the requested eventplate as @eventplate" do
      eventplate = Eventplate.create! valid_attributes
      get :show, {:id => eventplate.to_param}, valid_session
      assigns(:eventplate).should eq(eventplate)
    end
  end

  describe "GET new" do
    it "assigns a new eventplate as @eventplate" do
      get :new, {}, valid_session
      assigns(:eventplate).should be_a_new(Eventplate)
    end
  end

  describe "GET edit" do
    it "assigns the requested eventplate as @eventplate" do
      eventplate = Eventplate.create! valid_attributes
      get :edit, {:id => eventplate.to_param}, valid_session
      assigns(:eventplate).should eq(eventplate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Eventplate" do
        expect {
          post :create, {:eventplate => valid_attributes}, valid_session
        }.to change(Eventplate, :count).by(1)
      end

      it "assigns a newly created eventplate as @eventplate" do
        post :create, {:eventplate => valid_attributes}, valid_session
        assigns(:eventplate).should be_a(Eventplate)
        assigns(:eventplate).should be_persisted
      end

      it "redirects to the created eventplate" do
        post :create, {:eventplate => valid_attributes}, valid_session
        response.should redirect_to(Eventplate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved eventplate as @eventplate" do
        # Trigger the behavior that occurs when invalid params are submitted
        Eventplate.any_instance.stub(:save).and_return(false)
        post :create, {:eventplate => { "eventplanner_id" => "invalid value" }}, valid_session
        assigns(:eventplate).should be_a_new(Eventplate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Eventplate.any_instance.stub(:save).and_return(false)
        post :create, {:eventplate => { "eventplanner_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested eventplate" do
        eventplate = Eventplate.create! valid_attributes
        # Assuming there are no other eventplates in the database, this
        # specifies that the Eventplate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Eventplate.any_instance.should_receive(:update).with({ "eventplanner_id" => "1" })
        put :update, {:id => eventplate.to_param, :eventplate => { "eventplanner_id" => "1" }}, valid_session
      end

      it "assigns the requested eventplate as @eventplate" do
        eventplate = Eventplate.create! valid_attributes
        put :update, {:id => eventplate.to_param, :eventplate => valid_attributes}, valid_session
        assigns(:eventplate).should eq(eventplate)
      end

      it "redirects to the eventplate" do
        eventplate = Eventplate.create! valid_attributes
        put :update, {:id => eventplate.to_param, :eventplate => valid_attributes}, valid_session
        response.should redirect_to(eventplate)
      end
    end

    describe "with invalid params" do
      it "assigns the eventplate as @eventplate" do
        eventplate = Eventplate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Eventplate.any_instance.stub(:save).and_return(false)
        put :update, {:id => eventplate.to_param, :eventplate => { "eventplanner_id" => "invalid value" }}, valid_session
        assigns(:eventplate).should eq(eventplate)
      end

      it "re-renders the 'edit' template" do
        eventplate = Eventplate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Eventplate.any_instance.stub(:save).and_return(false)
        put :update, {:id => eventplate.to_param, :eventplate => { "eventplanner_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested eventplate" do
      eventplate = Eventplate.create! valid_attributes
      expect {
        delete :destroy, {:id => eventplate.to_param}, valid_session
      }.to change(Eventplate, :count).by(-1)
    end

    it "redirects to the eventplates list" do
      eventplate = Eventplate.create! valid_attributes
      delete :destroy, {:id => eventplate.to_param}, valid_session
      response.should redirect_to(eventplates_url)
    end
  end

end
