require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProductitemsController do

  # This should return the minimal set of attributes required to create a valid
  # Productitem. As you add validations to Productitem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "product_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProductitemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all productitems as @productitems" do
      productitem = Productitem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:productitems).should eq([productitem])
    end
  end

  describe "GET show" do
    it "assigns the requested productitem as @productitem" do
      productitem = Productitem.create! valid_attributes
      get :show, {:id => productitem.to_param}, valid_session
      assigns(:productitem).should eq(productitem)
    end
  end

  describe "GET new" do
    it "assigns a new productitem as @productitem" do
      get :new, {}, valid_session
      assigns(:productitem).should be_a_new(Productitem)
    end
  end

  describe "GET edit" do
    it "assigns the requested productitem as @productitem" do
      productitem = Productitem.create! valid_attributes
      get :edit, {:id => productitem.to_param}, valid_session
      assigns(:productitem).should eq(productitem)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Productitem" do
        expect {
          post :create, {:productitem => valid_attributes}, valid_session
        }.to change(Productitem, :count).by(1)
      end

      it "assigns a newly created productitem as @productitem" do
        post :create, {:productitem => valid_attributes}, valid_session
        assigns(:productitem).should be_a(Productitem)
        assigns(:productitem).should be_persisted
      end

      it "redirects to the created productitem" do
        post :create, {:productitem => valid_attributes}, valid_session
        response.should redirect_to(Productitem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved productitem as @productitem" do
        # Trigger the behavior that occurs when invalid params are submitted
        Productitem.any_instance.stub(:save).and_return(false)
        post :create, {:productitem => { "product_id" => "invalid value" }}, valid_session
        assigns(:productitem).should be_a_new(Productitem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Productitem.any_instance.stub(:save).and_return(false)
        post :create, {:productitem => { "product_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested productitem" do
        productitem = Productitem.create! valid_attributes
        # Assuming there are no other productitems in the database, this
        # specifies that the Productitem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Productitem.any_instance.should_receive(:update).with({ "product_id" => "1" })
        put :update, {:id => productitem.to_param, :productitem => { "product_id" => "1" }}, valid_session
      end

      it "assigns the requested productitem as @productitem" do
        productitem = Productitem.create! valid_attributes
        put :update, {:id => productitem.to_param, :productitem => valid_attributes}, valid_session
        assigns(:productitem).should eq(productitem)
      end

      it "redirects to the productitem" do
        productitem = Productitem.create! valid_attributes
        put :update, {:id => productitem.to_param, :productitem => valid_attributes}, valid_session
        response.should redirect_to(productitem)
      end
    end

    describe "with invalid params" do
      it "assigns the productitem as @productitem" do
        productitem = Productitem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Productitem.any_instance.stub(:save).and_return(false)
        put :update, {:id => productitem.to_param, :productitem => { "product_id" => "invalid value" }}, valid_session
        assigns(:productitem).should eq(productitem)
      end

      it "re-renders the 'edit' template" do
        productitem = Productitem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Productitem.any_instance.stub(:save).and_return(false)
        put :update, {:id => productitem.to_param, :productitem => { "product_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested productitem" do
      productitem = Productitem.create! valid_attributes
      expect {
        delete :destroy, {:id => productitem.to_param}, valid_session
      }.to change(Productitem, :count).by(-1)
    end

    it "redirects to the productitems list" do
      productitem = Productitem.create! valid_attributes
      delete :destroy, {:id => productitem.to_param}, valid_session
      response.should redirect_to(productitems_url)
    end
  end

end
